//! Stateful TEAL source for the native OpenNodia AMM.
//!
//! The program validates the transaction-group layouts generated by this crate
//! and performs the pool state transitions for CPMM bootstrap, add/remove
//! liquidity, and exact-input swaps.

use crate::{
    APP_ARG_ADD, APP_ARG_BOOTSTRAP, APP_ARG_CREATE, APP_ARG_REGISTER, APP_ARG_REMOVE,
    APP_ARG_SETUP, APP_ARG_SWAP, CONTRACT_VERSION_V3, CURRENT_CONTRACT_VERSION, CURVE_CPMM_V1,
    FEE_DENOMINATOR_BPS, GLOBAL_KEY_ASSET_0, GLOBAL_KEY_ASSET_1, GLOBAL_KEY_CURVE_ID,
    GLOBAL_KEY_FEE_BPS, GLOBAL_KEY_LP_ASSET, GLOBAL_KEY_POOL_APPROVAL_HASH,
    GLOBAL_KEY_POOL_CLEAR_HASH, GLOBAL_KEY_POOL_KEY, GLOBAL_KEY_REGISTRY_ACTIVE_COUNT,
    GLOBAL_KEY_REGISTRY_GENESIS_HASH, GLOBAL_KEY_REGISTRY_VERSION, GLOBAL_KEY_RESERVE_0,
    GLOBAL_KEY_RESERVE_1, GLOBAL_KEY_TOTAL_LP, GLOBAL_KEY_VERSION, MAX_AMM_TXN_FEE, MAX_LP_SUPPLY,
    MINIMUM_LOCKED_LP, REGISTRY_BOX_VALUE_BYTES,
};

pub const TEAL_VERSION: u64 = 8;
pub const REGISTRY_TEAL_VERSION: u64 = 8;
pub const CLEAR_STATE_SOURCE: &str = "#pragma version 8\nint 1\n";

pub fn clear_state_source() -> &'static str {
    CLEAR_STATE_SOURCE
}

pub fn approval_program_source() -> String {
    approval_program_source_for_version(CURRENT_CONTRACT_VERSION)
}

pub fn approval_program_source_for_version(contract_version: u16) -> String {
    let swap_block = if contract_version >= CONTRACT_VERSION_V3 {
        swap_exact_in_v3_source()
    } else {
        swap_exact_in_v2_source()
    };
    format!(
        r#"#pragma version {version}
txn RekeyTo
global ZeroAddress
==
assert
txn Fee
int {max_txn_fee}
<=
assert
txn ApplicationID
int 0
==
bnz create
txn OnCompletion
int NoOp
==
assert
txn NumAppArgs
int 1
>=
assert
txna ApplicationArgs 0
byte "{setup}"
==
bnz setup
txna ApplicationArgs 0
byte "{bootstrap}"
==
bnz bootstrap
txna ApplicationArgs 0
byte "{add}"
==
bnz add_liquidity
txna ApplicationArgs 0
byte "{remove}"
==
bnz remove_liquidity
txna ApplicationArgs 0
byte "{swap}"
==
bnz swap_exact_in
err

create:
txn OnCompletion
int NoOp
==
assert
txn NumAppArgs
int 5
==
assert
txna ApplicationArgs 0
byte "{create}"
==
assert
txna ApplicationArgs 4
len
int 32
==
assert
txna ApplicationArgs 1
btoi
txna ApplicationArgs 2
btoi
<
assert
txna ApplicationArgs 3
btoi
int 5
==
txna ApplicationArgs 3
btoi
int 30
==
||
txna ApplicationArgs 3
btoi
int 100
==
||
assert
byte "{asset_0}"
txna ApplicationArgs 1
btoi
app_global_put
byte "{asset_1}"
txna ApplicationArgs 2
btoi
app_global_put
byte "{curve_id}"
int {curve}
app_global_put
byte "{fee_bps}"
txna ApplicationArgs 3
btoi
app_global_put
byte "{version_key}"
int {contract_version}
app_global_put
byte "{lp_asset}"
int 0
app_global_put
byte "{reserve_0}"
int 0
app_global_put
byte "{reserve_1}"
int 0
app_global_put
byte "{total_lp}"
int 0
app_global_put
byte "{pool_key}"
txna ApplicationArgs 4
app_global_put
int 1
return

setup:
global GroupSize
int 2
==
assert
gtxn 0 TypeEnum
int pay
==
assert
gtxn 0 Receiver
global CurrentApplicationAddress
==
assert
gtxn 0 CloseRemainderTo
global ZeroAddress
==
assert
gtxn 0 RekeyTo
global ZeroAddress
==
assert
gtxn 0 Fee
int {max_txn_fee}
<=
assert
gtxn 1 Sender
gtxn 0 Sender
==
assert
txn GroupIndex
int 1
==
assert
byte "{lp_asset}"
app_global_get
int 0
==
assert
gtxn 1 NumAssets
int 2
<=
assert
int 0
callsub opt_in_asset
int 1
callsub opt_in_asset
itxn_begin
int acfg
itxn_field TypeEnum
int {max_lp_supply}
itxn_field ConfigAssetTotal
int 6
itxn_field ConfigAssetDecimals
byte "NODIALP"
itxn_field ConfigAssetUnitName
byte "OpenNodia LP"
itxn_field ConfigAssetName
global CurrentApplicationAddress
itxn_field ConfigAssetReserve
int 0
itxn_field Fee
itxn_submit
byte "{lp_asset}"
itxn CreatedAssetID
app_global_put
int 1
return

opt_in_asset:
store 0
load 0
txn NumAssets
<
bnz maybe_opt_in_asset
retsub
maybe_opt_in_asset:
load 0
txnas Assets
store 1
load 1
byte "{asset_0}"
app_global_get
==
load 1
byte "{asset_1}"
app_global_get
==
||
assert
load 1
int 0
==
bnz skip_opt_in_asset
itxn_begin
int axfer
itxn_field TypeEnum
load 1
itxn_field XferAsset
int 0
itxn_field AssetAmount
global CurrentApplicationAddress
itxn_field AssetReceiver
int 0
itxn_field Fee
itxn_submit
skip_opt_in_asset:
retsub

bootstrap:
txn GroupIndex
int 2
==
assert
global GroupSize
int 3
==
assert
txn NumAppArgs
int 3
==
assert
global Round
txna ApplicationArgs 2
btoi
<=
assert
byte "{lp_asset}"
app_global_get
int 0
>
assert
byte "{reserve_0}"
app_global_get
int 0
==
assert
byte "{reserve_1}"
app_global_get
int 0
==
assert
gtxn 0 Sender
txn Sender
==
assert
gtxn 1 Sender
txn Sender
==
byte "{asset_0}"
app_global_get
callsub check_deposit_0
store 2
byte "{asset_1}"
app_global_get
callsub check_deposit_1
store 3
load 2
int 0
>
assert
load 3
int 0
>
assert
load 2
itob
load 3
itob
b*
bsqrt
btoi
int {minimum_locked_lp}
>
assert
load 2
itob
load 3
itob
b*
bsqrt
btoi
int {minimum_locked_lp}
-
store 4
load 4
txna ApplicationArgs 1
btoi
>=
assert
byte "{reserve_0}"
load 2
app_global_put
byte "{reserve_1}"
load 3
app_global_put
byte "{total_lp}"
load 4
int {minimum_locked_lp}
+
app_global_put
byte "{lp_asset}"
app_global_get
load 4
callsub send_asset
int 1
return

add_liquidity:
txn GroupIndex
int 2
==
assert
global GroupSize
int 3
==
assert
txn NumAppArgs
int 3
==
assert
global Round
txna ApplicationArgs 2
btoi
<=
assert
byte "{reserve_0}"
app_global_get
int 0
>
assert
byte "{reserve_1}"
app_global_get
int 0
>
assert
gtxn 0 Sender
txn Sender
==
assert
gtxn 1 Sender
txn Sender
==
assert
byte "{asset_0}"
app_global_get
callsub check_deposit_0
store 2
byte "{asset_1}"
app_global_get
callsub check_deposit_1
store 3
load 2
itob
byte "{total_lp}"
app_global_get
itob
b*
byte "{reserve_0}"
app_global_get
itob
b/
btoi
store 4
load 3
itob
byte "{total_lp}"
app_global_get
itob
b*
byte "{reserve_1}"
app_global_get
itob
b/
btoi
store 5
load 4
load 5
<=
bnz add_use_0
load 5
store 6
b add_minted_ready
add_use_0:
load 4
store 6
add_minted_ready:
load 6
int 0
>
assert
load 6
txna ApplicationArgs 1
btoi
>=
assert
byte "{reserve_0}"
byte "{reserve_0}"
app_global_get
load 2
+
app_global_put
byte "{reserve_1}"
byte "{reserve_1}"
app_global_get
load 3
+
app_global_put
byte "{total_lp}"
byte "{total_lp}"
app_global_get
load 6
+
app_global_put
byte "{lp_asset}"
app_global_get
load 6
callsub send_asset
int 1
return

remove_liquidity:
txn GroupIndex
int 1
==
assert
global GroupSize
int 2
==
assert
txn NumAppArgs
int 4
==
assert
global Round
txna ApplicationArgs 3
btoi
<=
assert
gtxn 0 TypeEnum
int axfer
==
assert
gtxn 0 Sender
txn Sender
==
assert
gtxn 0 AssetReceiver
global CurrentApplicationAddress
==
assert
gtxn 0 XferAsset
byte "{lp_asset}"
app_global_get
==
assert
gtxn 0 AssetCloseTo
global ZeroAddress
==
assert
gtxn 0 RekeyTo
global ZeroAddress
==
assert
gtxn 0 Fee
int {max_txn_fee}
<=
assert
gtxn 0 AssetAmount
store 2
load 2
int 0
>
assert
byte "{total_lp}"
app_global_get
load 2
-
int {minimum_locked_lp}
>=
assert
load 2
itob
byte "{reserve_0}"
app_global_get
itob
b*
byte "{total_lp}"
app_global_get
itob
b/
btoi
store 3
load 2
itob
byte "{reserve_1}"
app_global_get
itob
b*
byte "{total_lp}"
app_global_get
itob
b/
btoi
store 4
load 3
txna ApplicationArgs 1
btoi
>=
assert
load 4
txna ApplicationArgs 2
btoi
>=
assert
byte "{reserve_0}"
byte "{reserve_0}"
app_global_get
load 3
-
app_global_put
byte "{reserve_1}"
byte "{reserve_1}"
app_global_get
load 4
-
app_global_put
byte "{total_lp}"
byte "{total_lp}"
app_global_get
load 2
-
app_global_put
byte "{asset_0}"
app_global_get
load 3
callsub send_asset
byte "{asset_1}"
app_global_get
load 4
callsub send_asset
int 1
return

{swap_block}

check_deposit_0:
store 8
load 8
byte "{asset_0}"
app_global_get
==
bnz check_deposit_0_common
load 8
byte "{asset_1}"
app_global_get
==
assert
check_deposit_0_common:
load 8
int 0
==
bnz check_deposit_0_algo
gtxn 0 TypeEnum
int axfer
==
assert
gtxn 0 XferAsset
load 8
==
assert
gtxn 0 AssetReceiver
global CurrentApplicationAddress
==
assert
gtxn 0 AssetSender
global ZeroAddress
==
assert
gtxn 0 AssetCloseTo
global ZeroAddress
==
assert
gtxn 0 RekeyTo
global ZeroAddress
==
assert
gtxn 0 Fee
int {max_txn_fee}
<=
assert
gtxn 0 AssetAmount
retsub
check_deposit_0_algo:
gtxn 0 TypeEnum
int pay
==
assert
gtxn 0 Receiver
global CurrentApplicationAddress
==
assert
gtxn 0 CloseRemainderTo
global ZeroAddress
==
assert
gtxn 0 RekeyTo
global ZeroAddress
==
assert
gtxn 0 Fee
int {max_txn_fee}
<=
assert
gtxn 0 Amount
retsub

check_deposit_1:
store 8
load 8
byte "{asset_0}"
app_global_get
==
bnz check_deposit_1_common
load 8
byte "{asset_1}"
app_global_get
==
assert
check_deposit_1_common:
load 8
int 0
==
bnz check_deposit_1_algo
gtxn 1 TypeEnum
int axfer
==
assert
gtxn 1 XferAsset
load 8
==
assert
gtxn 1 AssetReceiver
global CurrentApplicationAddress
==
assert
gtxn 1 AssetSender
global ZeroAddress
==
assert
gtxn 1 AssetCloseTo
global ZeroAddress
==
assert
gtxn 1 RekeyTo
global ZeroAddress
==
assert
gtxn 1 Fee
int {max_txn_fee}
<=
assert
gtxn 1 AssetAmount
retsub
check_deposit_1_algo:
gtxn 1 TypeEnum
int pay
==
assert
gtxn 1 Receiver
global CurrentApplicationAddress
==
assert
gtxn 1 CloseRemainderTo
global ZeroAddress
==
assert
gtxn 1 RekeyTo
global ZeroAddress
==
assert
gtxn 1 Fee
int {max_txn_fee}
<=
assert
gtxn 1 Amount
retsub

send_asset:
store 10
store 9
load 10
int 0
>
assert
load 9
int 0
==
bnz send_algo
itxn_begin
int axfer
itxn_field TypeEnum
load 9
itxn_field XferAsset
load 10
itxn_field AssetAmount
txn Sender
itxn_field AssetReceiver
int 0
itxn_field Fee
itxn_submit
retsub
send_algo:
itxn_begin
int pay
itxn_field TypeEnum
load 10
itxn_field Amount
txn Sender
itxn_field Receiver
int 0
itxn_field Fee
itxn_submit
retsub

disabled_write:
err
"#,
        version = TEAL_VERSION,
        create = ascii(APP_ARG_CREATE),
        setup = ascii(APP_ARG_SETUP),
        bootstrap = ascii(APP_ARG_BOOTSTRAP),
        add = ascii(APP_ARG_ADD),
        remove = ascii(APP_ARG_REMOVE),
        swap = ascii(APP_ARG_SWAP),
        swap_block = swap_block,
        asset_0 = ascii(GLOBAL_KEY_ASSET_0),
        asset_1 = ascii(GLOBAL_KEY_ASSET_1),
        curve_id = ascii(GLOBAL_KEY_CURVE_ID),
        fee_bps = ascii(GLOBAL_KEY_FEE_BPS),
        version_key = ascii(GLOBAL_KEY_VERSION),
        lp_asset = ascii(GLOBAL_KEY_LP_ASSET),
        reserve_0 = ascii(GLOBAL_KEY_RESERVE_0),
        reserve_1 = ascii(GLOBAL_KEY_RESERVE_1),
        total_lp = ascii(GLOBAL_KEY_TOTAL_LP),
        pool_key = ascii(GLOBAL_KEY_POOL_KEY),
        curve = CURVE_CPMM_V1,
        contract_version = contract_version,
        max_lp_supply = MAX_LP_SUPPLY,
        minimum_locked_lp = MINIMUM_LOCKED_LP,
        max_txn_fee = MAX_AMM_TXN_FEE,
    )
}

fn swap_exact_in_v2_source() -> String {
    format!(
        r#"swap_exact_in:
txn GroupIndex
int 1
==
assert
global GroupSize
int 2
==
assert
txn NumAppArgs
int 4
==
assert
global Round
txna ApplicationArgs 3
btoi
<=
assert
gtxn 0 Sender
txn Sender
==
assert
txna ApplicationArgs 1
btoi
byte "{asset_0}"
app_global_get
==
bnz swap_asset_0_in
txna ApplicationArgs 1
btoi
byte "{asset_1}"
app_global_get
==
assert
byte "{asset_1}"
app_global_get
callsub check_deposit_0
store 2
byte "{reserve_1}"
app_global_get
store 3
byte "{reserve_0}"
app_global_get
store 4
byte "{asset_0}"
app_global_get
store 5
b swap_compute
swap_asset_0_in:
byte "{asset_0}"
app_global_get
callsub check_deposit_0
store 2
byte "{reserve_0}"
app_global_get
store 3
byte "{reserve_1}"
app_global_get
store 4
byte "{asset_1}"
app_global_get
store 5
swap_compute:
load 2
int 0
>
assert
load 2
itob
int {fee_denominator_bps}
byte "{fee_bps}"
app_global_get
-
itob
b*
store 6
load 6
load 4
itob
b*
store 11
load 3
itob
int {fee_denominator_bps}
itob
b*
load 6
b+
store 12
load 11
load 12
b/
btoi
store 7
load 7
txna ApplicationArgs 2
btoi
>=
assert
load 7
int 0
>
assert
load 7
load 4
<
assert
txna ApplicationArgs 1
btoi
byte "{asset_0}"
app_global_get
==
bnz swap_update_asset_0_in
byte "{reserve_1}"
load 3
load 2
+
app_global_put
byte "{reserve_0}"
load 4
load 7
-
app_global_put
b swap_send
swap_update_asset_0_in:
byte "{reserve_0}"
load 3
load 2
+
app_global_put
byte "{reserve_1}"
load 4
load 7
-
app_global_put
swap_send:
load 5
load 7
callsub send_asset
int 1
return
"#,
        asset_0 = ascii(GLOBAL_KEY_ASSET_0),
        asset_1 = ascii(GLOBAL_KEY_ASSET_1),
        fee_bps = ascii(GLOBAL_KEY_FEE_BPS),
        reserve_0 = ascii(GLOBAL_KEY_RESERVE_0),
        reserve_1 = ascii(GLOBAL_KEY_RESERVE_1),
        fee_denominator_bps = FEE_DENOMINATOR_BPS,
    )
}

fn swap_exact_in_v3_source() -> String {
    format!(
        r#"swap_exact_in:
txn GroupIndex
int 0
>
assert
txn GroupIndex
int 1
-
store 13
load 13
gtxns Sender
txn Sender
==
assert
txn NumAppArgs
int 4
==
assert
global Round
txna ApplicationArgs 3
btoi
<=
assert
txna ApplicationArgs 1
btoi
byte "{asset_0}"
app_global_get
==
bnz swap_asset_0_in
txna ApplicationArgs 1
btoi
byte "{asset_1}"
app_global_get
==
assert
byte "{asset_1}"
app_global_get
callsub check_swap_deposit
store 2
byte "{reserve_1}"
app_global_get
store 3
byte "{reserve_0}"
app_global_get
store 4
byte "{asset_0}"
app_global_get
store 5
b swap_compute
swap_asset_0_in:
byte "{asset_0}"
app_global_get
callsub check_swap_deposit
store 2
byte "{reserve_0}"
app_global_get
store 3
byte "{reserve_1}"
app_global_get
store 4
byte "{asset_1}"
app_global_get
store 5
swap_compute:
load 2
int 0
>
assert
load 2
itob
int {fee_denominator_bps}
byte "{fee_bps}"
app_global_get
-
itob
b*
store 6
load 6
load 4
itob
b*
store 11
load 3
itob
int {fee_denominator_bps}
itob
b*
load 6
b+
store 12
load 11
load 12
b/
btoi
store 7
load 7
txna ApplicationArgs 2
btoi
>=
assert
load 7
int 0
>
assert
load 7
load 4
<
assert
txna ApplicationArgs 1
btoi
byte "{asset_0}"
app_global_get
==
bnz swap_update_asset_0_in
byte "{reserve_1}"
load 3
load 2
+
app_global_put
byte "{reserve_0}"
load 4
load 7
-
app_global_put
b swap_send
swap_update_asset_0_in:
byte "{reserve_0}"
load 3
load 2
+
app_global_put
byte "{reserve_1}"
load 4
load 7
-
app_global_put
swap_send:
load 5
load 7
callsub send_asset
int 1
return

check_swap_deposit:
store 8
load 8
byte "{asset_0}"
app_global_get
==
bnz check_swap_deposit_common
load 8
byte "{asset_1}"
app_global_get
==
assert
check_swap_deposit_common:
load 8
int 0
==
bnz check_swap_deposit_algo
load 13
gtxns TypeEnum
int axfer
==
assert
load 13
gtxns XferAsset
load 8
==
assert
load 13
gtxns AssetReceiver
global CurrentApplicationAddress
==
assert
load 13
gtxns AssetSender
global ZeroAddress
==
assert
load 13
gtxns AssetCloseTo
global ZeroAddress
==
assert
load 13
gtxns RekeyTo
global ZeroAddress
==
assert
load 13
gtxns Fee
int {max_txn_fee}
<=
assert
load 13
gtxns AssetAmount
retsub
check_swap_deposit_algo:
load 13
gtxns TypeEnum
int pay
==
assert
load 13
gtxns Receiver
global CurrentApplicationAddress
==
assert
load 13
gtxns CloseRemainderTo
global ZeroAddress
==
assert
load 13
gtxns RekeyTo
global ZeroAddress
==
assert
load 13
gtxns Fee
int {max_txn_fee}
<=
assert
load 13
gtxns Amount
retsub
"#,
        asset_0 = ascii(GLOBAL_KEY_ASSET_0),
        asset_1 = ascii(GLOBAL_KEY_ASSET_1),
        fee_bps = ascii(GLOBAL_KEY_FEE_BPS),
        reserve_0 = ascii(GLOBAL_KEY_RESERVE_0),
        reserve_1 = ascii(GLOBAL_KEY_RESERVE_1),
        fee_denominator_bps = FEE_DENOMINATOR_BPS,
        max_txn_fee = MAX_AMM_TXN_FEE,
    )
}

pub fn registry_approval_program_source() -> String {
    format!(
        r#"#pragma version {version}
txn RekeyTo
global ZeroAddress
==
assert
txn Fee
int {max_txn_fee}
<=
assert
txn ApplicationID
int 0
==
bnz registry_create
txn OnCompletion
int NoOp
==
assert
txn NumAppArgs
int 1
>=
assert
txna ApplicationArgs 0
byte "{register}"
==
bnz register_pool
err

registry_create:
txn OnCompletion
int NoOp
==
assert
txn NumAppArgs
int 4
==
assert
txna ApplicationArgs 0
byte "{create}"
==
assert
txna ApplicationArgs 1
len
int 32
==
assert
txna ApplicationArgs 2
len
int 32
==
assert
txna ApplicationArgs 3
len
int 32
==
assert
byte "{registry_version_key}"
int 1
app_global_put
byte "{genesis_hash_key}"
txna ApplicationArgs 1
app_global_put
byte "{pool_approval_hash}"
txna ApplicationArgs 2
app_global_put
byte "{pool_clear_hash}"
txna ApplicationArgs 3
app_global_put
byte "{active_count}"
int 0
app_global_put
int 1
return

register_pool:
txn GroupIndex
int 2
==
assert
global GroupSize
int 3
==
assert
txn NumAppArgs
int 2
==
assert
txna ApplicationArgs 1
len
int 32
==
assert
gtxn 0 Sender
txn Sender
==
assert
gtxn 1 Sender
txn Sender
==
assert
gtxn 0 RekeyTo
global ZeroAddress
==
assert
gtxn 0 Fee
int {max_txn_fee}
<=
assert
gtxn 1 TypeEnum
int pay
==
assert
gtxn 1 Receiver
global CurrentApplicationAddress
==
assert
gtxn 1 Amount
int {box_min_balance}
byte "{active_count}"
app_global_get
int 0
==
int {registry_base_min_balance}
*
+
>=
assert
gtxn 1 CloseRemainderTo
global ZeroAddress
==
assert
gtxn 1 RekeyTo
global ZeroAddress
==
assert
gtxn 1 Fee
int {max_txn_fee}
<=
assert
gtxn 0 TypeEnum
int appl
==
assert
gtxn 0 ApplicationID
int 0
==
assert
gtxn 0 OnCompletion
int NoOp
==
assert
gtxn 0 NumAppArgs
int 5
==
assert
gtxna 0 ApplicationArgs 0
byte "{create}"
==
assert
gtxna 0 ApplicationArgs 1
len
int 8
==
assert
gtxna 0 ApplicationArgs 2
len
int 8
==
assert
gtxna 0 ApplicationArgs 3
len
int 8
==
assert
gtxna 0 ApplicationArgs 1
btoi
gtxna 0 ApplicationArgs 2
btoi
<
assert
gtxna 0 ApplicationArgs 3
btoi
int 5
==
gtxna 0 ApplicationArgs 3
btoi
int 30
==
||
gtxna 0 ApplicationArgs 3
btoi
int 100
==
||
assert
byte "OpenNodiaPoolKeyV1"
byte "{genesis_hash_key}"
app_global_get
concat
gtxna 0 ApplicationArgs 1
concat
gtxna 0 ApplicationArgs 2
concat
int {curve}
itob
substring 6 8
concat
gtxna 0 ApplicationArgs 3
substring 6 8
concat
int {contract_version}
itob
substring 6 8
concat
sha512_256
txna ApplicationArgs 1
==
assert
gtxna 0 ApplicationArgs 4
txna ApplicationArgs 1
==
assert
gtxn 0 ApprovalProgram
sha512_256
byte "{pool_approval_hash}"
app_global_get
==
assert
gtxn 0 ClearStateProgram
sha512_256
byte "{pool_clear_hash}"
app_global_get
==
assert
txna ApplicationArgs 1
int {box_value_bytes}
box_create
assert
txna ApplicationArgs 1
gtxn 0 CreatedApplicationID
itob
box_put
byte "{active_count}"
byte "{active_count}"
app_global_get
int 1
+
app_global_put
int 1
return
"#,
        version = REGISTRY_TEAL_VERSION,
        max_txn_fee = MAX_AMM_TXN_FEE,
        create = String::from_utf8_lossy(APP_ARG_CREATE),
        register = String::from_utf8_lossy(APP_ARG_REGISTER),
        registry_version_key = String::from_utf8_lossy(GLOBAL_KEY_REGISTRY_VERSION),
        genesis_hash_key = String::from_utf8_lossy(GLOBAL_KEY_REGISTRY_GENESIS_HASH),
        pool_approval_hash = String::from_utf8_lossy(GLOBAL_KEY_POOL_APPROVAL_HASH),
        pool_clear_hash = String::from_utf8_lossy(GLOBAL_KEY_POOL_CLEAR_HASH),
        active_count = String::from_utf8_lossy(GLOBAL_KEY_REGISTRY_ACTIVE_COUNT),
        box_value_bytes = REGISTRY_BOX_VALUE_BYTES,
        box_min_balance = crate::REGISTRY_BOX_MIN_BALANCE_MICROALGO,
        registry_base_min_balance = crate::REGISTRY_APP_BASE_MIN_BALANCE_MICROALGO,
        curve = CURVE_CPMM_V1,
        contract_version = CURRENT_CONTRACT_VERSION,
    )
}

fn ascii(bytes: &[u8]) -> &str {
    std::str::from_utf8(bytes).expect("AMM contract keys are ASCII")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_contains_all(source: &str, snippets: &[&str]) {
        for snippet in snippets {
            assert!(
                source.contains(snippet),
                "expected source to contain snippet:\n{snippet}"
            );
        }
    }

    #[test]
    fn approval_source_declares_state_keys_and_methods() {
        let source = approval_program_source();
        assert!(source.contains("#pragma version 8"));
        assert!(source.contains("create:"));
        assert!(source.contains("setup:"));
        assert!(source.contains("bootstrap:"));
        assert!(source.contains("add_liquidity:"));
        assert!(source.contains("remove_liquidity:"));
        assert!(source.contains("swap_exact_in:"));
        assert!(source.contains("byte \"asset_0\""));
        assert!(source.contains("byte \"lp_asset\""));
        assert!(source.contains("itxn CreatedAssetID"));
        assert!(source.contains(
            "remove_liquidity:\ntxn GroupIndex\nint 1\n==\nassert\nglobal GroupSize\nint 2"
        ));
    }

    #[test]
    fn approval_source_enforces_universal_call_guards() {
        let source = approval_program_source();
        assert_contains_all(
            &source,
            &[
                "txn RekeyTo\nglobal ZeroAddress\n==\nassert",
                "txn Fee\nint 20000\n<=\nassert",
                "txn OnCompletion\nint NoOp\n==\nassert",
                "txn NumAppArgs\nint 1\n>=\nassert",
            ],
        );
    }

    #[test]
    fn bootstrap_and_add_guard_matrix_is_present() {
        let source = approval_program_source();
        assert_contains_all(
            &source,
            &[
                "bootstrap:\ntxn GroupIndex\nint 2\n==\nassert\nglobal GroupSize\nint 3",
                "add_liquidity:\ntxn GroupIndex\nint 2\n==\nassert\nglobal GroupSize\nint 3",
                "global Round\ntxna ApplicationArgs 2\nbtoi\n<=\nassert",
                "gtxn 0 Sender\ntxn Sender\n==\nassert\ngtxn 1 Sender\ntxn Sender\n==",
                "byte \"asset_0\"\napp_global_get\ncallsub check_deposit_0",
                "byte \"asset_1\"\napp_global_get\ncallsub check_deposit_1",
                "load 6\ntxna ApplicationArgs 1\nbtoi\n>=\nassert",
            ],
        );
    }

    #[test]
    fn remove_guard_matrix_is_present() {
        let source = approval_program_source();
        assert_contains_all(
            &source,
            &[
                "remove_liquidity:\ntxn GroupIndex\nint 1\n==\nassert\nglobal GroupSize\nint 2",
                "txn NumAppArgs\nint 4\n==\nassert",
                "global Round\ntxna ApplicationArgs 3\nbtoi\n<=\nassert",
                "gtxn 0 XferAsset\nbyte \"lp_asset\"\napp_global_get\n==\nassert",
                "gtxn 0 AssetCloseTo\nglobal ZeroAddress\n==\nassert",
                "gtxn 0 RekeyTo\nglobal ZeroAddress\n==\nassert",
                "gtxn 0 Fee\nint 20000\n<=\nassert",
                "byte \"total_lp\"\napp_global_get\nload 2\n-\nint 1000\n>=\nassert",
                "load 3\ntxna ApplicationArgs 1\nbtoi\n>=\nassert",
                "load 4\ntxna ApplicationArgs 2\nbtoi\n>=\nassert",
            ],
        );
    }

    #[test]
    fn swap_v3_guard_matrix_is_present() {
        let source = approval_program_source_for_version(CONTRACT_VERSION_V3);
        assert_contains_all(
            &source,
            &[
                "swap_exact_in:\ntxn GroupIndex\nint 0\n>\nassert\ntxn GroupIndex\nint 1\n-",
                "load 13\ngtxns Sender\ntxn Sender\n==\nassert",
                "txn NumAppArgs\nint 4\n==\nassert",
                "global Round\ntxna ApplicationArgs 3\nbtoi\n<=\nassert",
                "txna ApplicationArgs 1\nbtoi\nbyte \"asset_0\"\napp_global_get\n==",
                "txna ApplicationArgs 1\nbtoi\nbyte \"asset_1\"\napp_global_get\n==\nassert",
                "callsub check_swap_deposit",
                "load 7\ntxna ApplicationArgs 2\nbtoi\n>=\nassert",
                "load 7\nint 0\n>\nassert",
                "load 7\nload 4\n<\nassert",
            ],
        );
    }

    #[test]
    fn deposit_subroutines_reject_close_rekey_and_fee_mutations() {
        let source = approval_program_source();
        assert_contains_all(
            &source,
            &[
                "gtxn 0 AssetSender\nglobal ZeroAddress\n==\nassert",
                "gtxn 0 AssetCloseTo\nglobal ZeroAddress\n==\nassert",
                "gtxn 0 CloseRemainderTo\nglobal ZeroAddress\n==\nassert",
                "gtxn 1 AssetSender\nglobal ZeroAddress\n==\nassert",
                "gtxn 1 AssetCloseTo\nglobal ZeroAddress\n==\nassert",
                "gtxn 1 CloseRemainderTo\nglobal ZeroAddress\n==\nassert",
                "load 13\ngtxns AssetSender\nglobal ZeroAddress\n==\nassert",
                "load 13\ngtxns AssetCloseTo\nglobal ZeroAddress\n==\nassert",
                "load 13\ngtxns CloseRemainderTo\nglobal ZeroAddress\n==\nassert",
                "load 13\ngtxns Fee\nint 20000\n<=\nassert",
            ],
        );
    }

    #[test]
    fn v2_swap_source_keeps_fixed_two_transaction_layout() {
        let source = approval_program_source_for_version(2);
        assert!(source.contains(
            "swap_exact_in:\ntxn GroupIndex\nint 1\n==\nassert\nglobal GroupSize\nint 2"
        ));
        assert!(source.contains("callsub check_deposit_0"));
        assert!(source.contains("gtxn 0 Sender\ntxn Sender\n==\nassert"));
        assert!(!source.contains("check_swap_deposit:"));
        assert!(!source.contains("gtxns Sender"));
    }

    #[test]
    fn v3_swap_source_uses_relative_deposit_checks() {
        let source = approval_program_source_for_version(CONTRACT_VERSION_V3);
        assert!(source.contains("swap_exact_in:\ntxn GroupIndex\nint 0\n>\nassert\ntxn GroupIndex"));
        assert!(source.contains("check_swap_deposit:"));
        assert!(source.contains("gtxns Sender\ntxn Sender\n==\nassert"));
        assert!(source.contains("callsub check_swap_deposit"));
        assert!(!source.contains(
            "swap_exact_in:\ntxn GroupIndex\nint 1\n==\nassert\nglobal GroupSize\nint 2"
        ));
    }

    #[test]
    fn registry_source_declares_box_registration() {
        let source = registry_approval_program_source();
        assert!(source.contains("#pragma version 8"));
        assert!(source.contains("registry_create:"));
        assert!(source.contains("register_pool:"));
        assert!(source.contains("box_create"));
        assert!(source.contains("box_put"));
        assert!(source.contains("byte \"genesis_hash\""));
        assert!(source.contains("app_global_get"));
        assert!(source.contains("gtxn 0 CreatedApplicationID"));
        assert!(source.contains(
            "register_pool:\ntxn GroupIndex\nint 2\n==\nassert\nglobal GroupSize\nint 3"
        ));
    }

    #[test]
    fn clear_state_is_unconditional() {
        assert_eq!(clear_state_source(), "#pragma version 8\nint 1\n");
    }
}
